#!/bin/sh
set -e

BASE="$1"
CHERRYPICK="$2"
TAG="$3"

cd RobustToolbox
git checkout "$BASE"
git cherry-pick "$CHERRYPICK"
git tag -f "$TAG"
COMMIT="`git rev-parse HEAD`"
cd ..

echo "$COMMIT" > "current.commit"
