#!/bin/sh

set -e

BASE="$1"
PATCH="$2"

cp "$PATCH" RobustToolbox/__patch.patch

cd RobustToolbox
git checkout "$BASE"
git am < __patch.patch
COMMIT="`git rev-parse HEAD`"
rm __patch.patch
cd ..

echo "$COMMIT" > "current.commit"
