#!/bin/sh

set -e

# Try to ensure a coherent tag list...
cd RobustToolbox
git fetch -t origin
git tag | grep "^v[0-9]" > tags_temp
cd ..

# Tag list is coherent
mv RobustToolbox/tags_temp tags

./driver.py
